# This file was generated by GoReleaser. DO NOT EDIT.
cask "ignoreinit" do
  name "ignoreinit"
  desc "A tool for creating .gitignore files from the command line"
  homepage "https://github.com/Loupeznik/ignoreinit"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ignoreinit"

  on_macos do
    on_intel do
      url "https://github.com/Loupeznik/ignoreinit/releases/download/v#{version}/ignoreinit_#{version}_darwin_amd64.tar.gz"
      sha256 "6486b8b1faa531d832fe10a5db91578ac97d90f25f3970ebfd0712888a7de667"
    end
    on_arm do
      url "https://github.com/Loupeznik/ignoreinit/releases/download/v#{version}/ignoreinit_#{version}_darwin_arm64.tar.gz"
      sha256 "deec36189048cf3df6542b248bde674c64198999a0bc8607e60d78262a4011ff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loupeznik/ignoreinit/releases/download/v#{version}/ignoreinit_#{version}_linux_amd64.tar.gz"
      sha256 "966f4f68b8eee19c8d90be54c18cca156ffaf9b838717695afd65e8181a10def"
    end
    on_arm do
      url "https://github.com/Loupeznik/ignoreinit/releases/download/v#{version}/ignoreinit_#{version}_linux_arm64.tar.gz"
      sha256 "8e9537f9390d0d47467fb9fafca2ecd0b1eefec844edd10ffc608a127e2d28a2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ignoreinit"]
    end
  end

  # No zap stanza required
end
