# This file was generated by GoReleaser. DO NOT EDIT.
cask "kcm" do
  name "kcm"
  desc "TUI + CLI for managing kubeconfig files and kubectl contexts"
  homepage "https://github.com/Loupeznik/kubeconfig-manager"
  version "0.10.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kcm"
  manpage "docs/man/kcm-alert-disable.1"
  manpage "docs/man/kcm-alert-enable.1"
  manpage "docs/man/kcm-alert-show.1"
  manpage "docs/man/kcm-alert.1"
  manpage "docs/man/kcm-audit.1"
  manpage "docs/man/kcm-context-delete.1"
  manpage "docs/man/kcm-context-rename.1"
  manpage "docs/man/kcm-context.1"
  manpage "docs/man/kcm-contexts.1"
  manpage "docs/man/kcm-doctor.1"
  manpage "docs/man/kcm-helm-guard-add-pattern.1"
  manpage "docs/man/kcm-helm-guard-disable.1"
  manpage "docs/man/kcm-helm-guard-enable.1"
  manpage "docs/man/kcm-helm-guard-fallback.1"
  manpage "docs/man/kcm-helm-guard-remove-pattern.1"
  manpage "docs/man/kcm-helm-guard-set-patterns.1"
  manpage "docs/man/kcm-helm-guard-show.1"
  manpage "docs/man/kcm-helm-guard.1"
  manpage "docs/man/kcm-helm.1"
  manpage "docs/man/kcm-import.1"
  manpage "docs/man/kcm-init.1"
  manpage "docs/man/kcm-install-shell-hook.1"
  manpage "docs/man/kcm-kubectl.1"
  manpage "docs/man/kcm-list.1"
  manpage "docs/man/kcm-merge.1"
  manpage "docs/man/kcm-prune.1"
  manpage "docs/man/kcm-rename.1"
  manpage "docs/man/kcm-show.1"
  manpage "docs/man/kcm-split.1"
  manpage "docs/man/kcm-starship.1"
  manpage "docs/man/kcm-tag-add.1"
  manpage "docs/man/kcm-tag-list.1"
  manpage "docs/man/kcm-tag-palette-add.1"
  manpage "docs/man/kcm-tag-palette-list.1"
  manpage "docs/man/kcm-tag-palette-remove.1"
  manpage "docs/man/kcm-tag-palette.1"
  manpage "docs/man/kcm-tag-remove.1"
  manpage "docs/man/kcm-tag.1"
  manpage "docs/man/kcm-tui.1"
  manpage "docs/man/kcm-uninstall-shell-hook.1"
  manpage "docs/man/kcm-use.1"
  manpage "docs/man/kcm.1"

  on_macos do
    on_intel do
      url "https://github.com/Loupeznik/kubeconfig-manager/releases/download/v#{version}/kubeconfig-manager_#{version}_darwin_amd64.tar.gz"
      sha256 "512351f1b7dc9ff1e7c30af371ef5a23ba2f24d20016a9da5505e688012493ed"
    end
    on_arm do
      url "https://github.com/Loupeznik/kubeconfig-manager/releases/download/v#{version}/kubeconfig-manager_#{version}_darwin_arm64.tar.gz"
      sha256 "2ade718ed0ce62999d5dadb2b0909466ca41c3c83527579cb695077b9e3b4d64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loupeznik/kubeconfig-manager/releases/download/v#{version}/kubeconfig-manager_#{version}_linux_amd64.tar.gz"
      sha256 "1e924848ee3ddb47b1329e92723478575d8ae500a67e0dcdbfde99da73ac4e4a"
    end
    on_arm do
      url "https://github.com/Loupeznik/kubeconfig-manager/releases/download/v#{version}/kubeconfig-manager_#{version}_linux_arm64.tar.gz"
      sha256 "f0c3b54745f6ff063c4817e979fd27d03406af531010fd9c042faa52b5135b57"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kcm"]
    end
  end

  # No zap stanza required
end
