# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcm < Formula
  desc "TUI + CLI for managing kubeconfig files and kubectl contexts"
  homepage "https://github.com/Loupeznik/kubeconfig-manager"
  version "0.10.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Loupeznik/kubeconfig-manager/releases/download/v0.10.1/kubeconfig-manager_0.10.1_darwin_amd64.tar.gz"
      sha256 "ced6ef094d6c27e4d4711febad12fa17816fa70c8b37123cf0dd57f3398201e1"

      define_method(:install) do
        bin.install "kcm"
        man1.install Dir["docs/man/*.1"]
        generate_completions_from_executable(bin/"kcm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Loupeznik/kubeconfig-manager/releases/download/v0.10.1/kubeconfig-manager_0.10.1_darwin_arm64.tar.gz"
      sha256 "aed5c012664ebaeaa3b59c2310a84fe22e564d3eead141009d334c496993f1ed"

      define_method(:install) do
        bin.install "kcm"
        man1.install Dir["docs/man/*.1"]
        generate_completions_from_executable(bin/"kcm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Loupeznik/kubeconfig-manager/releases/download/v0.10.1/kubeconfig-manager_0.10.1_linux_amd64.tar.gz"
      sha256 "5522dac4ec4e43983b16815be89ec00be602675ec700deb5d4b1c6ddea23ed0d"
      define_method(:install) do
        bin.install "kcm"
        man1.install Dir["docs/man/*.1"]
        generate_completions_from_executable(bin/"kcm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Loupeznik/kubeconfig-manager/releases/download/v0.10.1/kubeconfig-manager_0.10.1_linux_arm64.tar.gz"
      sha256 "9a2533a110f0f6042b0720516308a2324873994e556d2df717295760b1066c21"
      define_method(:install) do
        bin.install "kcm"
        man1.install Dir["docs/man/*.1"]
        generate_completions_from_executable(bin/"kcm", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/kcm", "--version"
  end
end
